secret: changeme
checks:
  - id: check-cloudflare
    type: http
    target: https://cloudflare.com
    webhook: https://hooks.example.com/your-url
  - id: check-google
    type: http
    target: https://google.com
  - id: check-tcp-example
    type: tcp
    target: example.com:443
  - id: check-dns-example
    type: dns
    target: example.com
